# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: library/postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "assembly"
    ports:
      - 5441:5432
    volumes:
      -  pg-data:/var/lib/postgresql/data
volumes:
  pg-data: